### ISSUE TITLE
[CharGen] Refresh and possible JS bug in equipment select

### ISSUE THREAD

**Issue by jdgwf** [jdgwf/savage-worlds-web-tools#30]
Definitely a reproducable refresh of dropdown problem caused by a possible JS error in equipment select. Noticed it on the iPad a couple of weeks ago.

**Comment by jdgwf** [comment]
Closing issue on pending rewrite of Equipment section.

**Comment by Galod** [comment]
This bug can be fixed by adding at line 1361 of character_creator.js this lines:
```javascript
if (typeof(current_gear_class)=="undefined")
			current_gear_class = "";
```
Bug also prevents hiding of confirmation dialogs (when you delete edge, complete character creation, etc.)
