### ISSUE TITLE
Gear selection fails silently

### ISSUE THREAD

**Issue by agryson** [jdgwf/savage-worlds-web-tools#47]
When playing around with gear dropdowns (moving from weapons to mundane after having set something as free etc.) there'll be a silent failure and addition selection won't work anymore.

Console says:

``` javascript
character_creator.js:1461
Uncaught TypeError: Cannot read property 'toLowerCase' of undefinedListPicker._handleMouseUp @ about:blank:554
character_creator.js:1461
Uncaught TypeError: Cannot read property 'toLowerCase' of undefinedListPicker._handleMouseUp @ about:blank:542
```

The if on line 1458 should probably do a check for if what its testing exists

**Comment by FTgremlin** [comment]
This is more noticeable with Sci-Fi companion.
1, Set Sci-Fi companion on
2, Access Sci-Fi book equipment
3, Go to armour
4, Attempt to change book or category
-- notice you're now locked in.

**Comment by jdgwf** [comment]
What browser? I'm having trouble duplicating on my end 

> character_creator.js:1461

There is no such JS file.

**Comment by jdgwf** [comment]
Wait. This is probably from the old version.

**Comment by jdgwf** [comment]
Closing out commit as it's invalid with new version
