### ISSUE TITLE
BUG: Heavy-G Worlder needs to set STR to d6

### ISSUE THREAD

**Issue by FTgremlin** [jdgwf/savage-worlds-web-tools#49]
Or at least give players a +1 attribute buy-in.

**Comment by jdgwf** [comment]
Heavy-G worlder is currently not available due to the extra hindrances rule exception (there aren't many edges that require an extra hindrance to be taken).

**Comment by jdgwf** [comment]
...and I was still wrapping my head around how to handle that.
