### ISSUE TITLE
BUG: Pricing for Melee Sci-Fi weapons is all wrong

### ISSUE THREAD

**Issue by FTgremlin** [jdgwf/savage-worlds-web-tools#50]
All weapons cost $500 when bought from the Melee Sci-Fi section.
This should actually be base cost +$500. So, eg. A chain long-sword should be $800 (300+500)

**Comment by jdgwf** [comment]
Yep. I'll have to enter each and every one of the melee weapons or find something else creative to fix this. It'll be a while.
