### ISSUE TITLE
[FEATURE] Savage Conversions support

### ISSUE THREAD

**Issue by timoc** [jdgwf/savage-worlds-web-tools#51]
How about adding Fan content such as Savage Eberron:
https://docs.google.com/document/d/1sE2Xa9aWOlHXfB3ZX14gdJLvxm3Lzs2qJfaJozlx1vQ/edit#

**Comment by jdgwf** [comment]
All that data is not handled by the Savage Fan license. I'd have to contact Kristian Serrano for permission on that, and then I'd have to worry about making sure that the Eberron copyrights are in too.

Right now I want to get everything stable before I start adding too many items.

It's possible! :)
