### ISSUE TITLE
Help with data entry?

### ISSUE THREAD

**Issue by Swampson** [jdgwf/savage-worlds-web-tools#52]
In the extras database, you have a tooltip comment indicating there is still a lot of data entry to be done. Is this something you'd like assistance with? I'd be happy to plug-in some details if you let me know how to do it and where to start.

**Comment by jdgwf** [comment]
Actually the core books are now fully added. I was going to add entries from the Savage Free Bestiary, but I've not got around to it. All the data manipulation is handled by a little PHP web app that creates the JS code. I can get you access to that if you're still interested.

**Comment by Swampson** [comment]
Apologies that I never replied back to you and just now noticed this now that you've closed the thread - if you'd still like help with data entry and can hook me up with the PHP web app you referred to I'd be happy to help out.
