### ISSUE TITLE
Style Change - buttons show variable names

### ISSUE THREAD

**Issue by FTgremlin** [jdgwf/savage-worlds-web-tools#53]
With the new style change, all buttons are now showing _variable names_ instead of their string names.
eg:
`INDEX_BUTTON_CORE_CHAR` instead of 'Create Character'.

**Comment by FTgremlin** [comment]
https://github.com/jdgwf/savage-worlds-web-tools/commit/ac010040638daf0214e72cacc0812ea8c8e31925
From this. It looks intentional, but it stops users from being able to use it properly. Especially when you get GENERAL_ERROR

**Comment by jdgwf** [comment]
It's a possibility that you're on a language that doesn't have a fi;; translation. Make sure that you're selected on English when submitting this/ I'm not seeing them. If your default browser language is set to German or Brazilian it's a very good possibility that the system may have picked up on your local language string and set the language up there automagically. 

Just set it to English until we can get translators on this.

**Comment by FTgremlin** [comment]
Default language was set to BLANK.
This may be relevant to raise as another bug.

**Comment by jdgwf** [comment]
Right on. Will revisit when there is interest in multilingual again.

Thank you!
