### ISSUE TITLE
Raise Trainer: Success with 4 Raises button has incorrect text

### ISSUE THREAD

**Issue by theloremaster** [jdgwf/savage-worlds-web-tools#54]
The Raise Trainer has a button for Success w/ 5 Raises, but according to the code, this should be Success w/ 4 Raises

`<button class="button primary expanded ng-scope" ng-click="clickSuccess4Raises()" translate="GENERAL_SUCCESS_4_RAISES">Success w/ 5 Raises</button>`

**Comment by jdgwf** [comment]
Nice. Easy language file typo - fixed on next commit later today EOB.

Thanks!
