### ISSUE TITLE
Raise Trainer: Success with 4 Raises button gives false failure

### ISSUE THREAD

**Issue by theloremaster** [jdgwf/savage-worlds-web-tools#55]
When using the Raise Trainer, and the result should be Success with 4 Raises, clicking the appropriate button will show an that it was chosen incorrectly. However, it will be logged as a correct response in the final results. 

![image](https://cloud.githubusercontent.com/assets/7747482/22450816/430568c0-e737-11e6-9779-ffaa877ceebb.png)
![image](https://cloud.githubusercontent.com/assets/7747482/22450834/6d34217c-e737-11e6-969a-edd27b31c15e.png)

**Comment by jdgwf** [comment]
Is this an effect of #54 - or is it actually a problem in the display?

**Comment by theloremaster** [comment]
I'm pretty sure it's a code issue. When the answer should be Raise + 4 Raises, clicking it gives an error. I don't know if fixing #54 resolves it, but it's worth testing.

**Comment by jdgwf** [comment]
You're absolutely right.. it is a code issue
https://github.com/jdgwf/savage-worlds-web-tools/blob/gh-pages/js/src/controllers/core-raise-trainer.js#L365

Testing against an unknown variable.. I'm in the middle of a huge refactoring of the chargen, it may be Friday before the fix goes live

THANK YOU!
