### ISSUE TITLE
Wrong hindrance setting: All thumbs should not be a racial hindrance

### ISSUE THREAD

**Issue by LoSmith** [jdgwf/savage-worlds-web-tools#57]
Page 28 SW - Deluxe Edition

you edited it as racial. But as far as i know it is just a normal Hindrance (minor).
../src/data/_hindrances.js

**Comment by jdgwf** [comment]
Actually I had set up the Racial Elf All Thumbs (there's a difference in the description) and forgot to add the primary one. Fix will be refreshed and incoming by EOB today.
