### ISSUE TITLE
Initial load doesn't set default language to en-US

### ISSUE THREAD

**Issue by FTgremlin** [jdgwf/savage-worlds-web-tools#59]
I see that in `js/src/_base_app.js` the default language (`users_preferred_language`) is set to `en-US`
When loading chrome in Incognito mode and accessing [the webapp](http://jdgwf.github.io/savage-worlds-web-tools/#/), the user's language remains unset.
I don't know if this is due to my machine, but I'd have expected it to default to en-US regardless.

**Comment by FTgremlin** [comment]
<img width="288" alt="screen shot 2017-03-22 at 14 52 19" src="https://cloud.githubusercontent.com/assets/12858421/24204033/2991174a-0f0f-11e7-8a34-85d3c6732f1b.png">

**Comment by jdgwf** [comment]
thats strange. I can't duplicate it in Chrome on Windows, Chromium in Linux, Firefox in Linux, Chrome on Mac or Safari on Mac.... or even private mode for Safari on iOS. Neither incognito or regular modes.. strange

**Comment by FTgremlin** [comment]
I'm wondering if it's something to do with the Mac environment. It's no biggie if I know how to fix it, though I had no clue about setting languages.

**Comment by jdgwf** [comment]
It's possible, but not on the 2 Mac systems I test on (caveat: all latest OS and Chrome updates)

![screen shot 2017-03-23 at 8 04 37](https://cloud.githubusercontent.com/assets/316824/24248963/883ac990-0f9f-11e7-8c5e-be81881ad728.png)

**Comment by jdgwf** [comment]
What country are you in? I'm wondering if the default country code acquisition code is trying to set to a language that doesn't exist. I'm probably better off just removing it and defaulting to en-US like I had it in the beginning.

**Comment by FTgremlin** [comment]
Based in the UK. I think it's under en-GB usually.

**Comment by jdgwf** [comment]
Yep that'd be it... it's different than en-US... The next push removes my 'automatic' bit of code and defaults to en-US again... in the future I may revisit it and search through installed and active languages :)
