### ISSUE TITLE
Starship Creator: Heavy/Medium Particle - misinformation

### ISSUE THREAD

**Issue by FTgremlin** [jdgwf/savage-worlds-web-tools#62]
The Heavy/Medium Particle Cannon lists it as 'Reaction Fire'.
This should only apply to the Light Particle Cannon.

You mention in the files that this is generated by something in the admin area. Is it possible to find these files to edit them/correct them so that we don't have to open an Issue each time?

**Comment by jdgwf** [comment]
Absolutely I can get you access :)

Sending you an email.
