### ISSUE TITLE
"New Power" edge always always displays error?

### ISSUE THREAD

**Issue by anse47103** [jdgwf/savage-worlds-web-tools#66]
Hey gang! I love this tool to hell and back, it makes pre-gens easier than breathing and helps my new PCs make sound characters without anything confusing to hold them back, so thanks for making the tool!
I've noticed that selecting the edge "New Power" always displays the error "Does not meet previous requirements", which doesn't make sense because the requirements are only Novice and some sort of AB, both of which the characters I've tried to make have had. Is this a known bug, or am I just doing a stupid of some sort?

Cheers, and thanks for the tool!
Anse

**Comment by jdgwf** [comment]
Sorry, it's just me (and crazy busy). This has been fixed - plus lots of other additions :)

**Comment by anse47103** [comment]
Many thanks for the fix and keeping such an amazing program operational! It's a huge asset at my table. Thanks for all the hard work :)

Best, 
Sean McClain
